eureka:
 client:
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://127.0.0.1:8761/eureka/}

spring:
  application:
    name: gateway-server

server:
  port: 9000

turbine:
  stream:
    port: 8989
#  aggregator:
#    clusterConfig: joker
#  appConfig: examinator-service,math-service,gateway-server,theology-service
