theology:
  questions-and-answers:
    "не грешно ли лезть в атом?": "nope"
    "аннотации это грех?": "только если тебя зовут Егор"
    "Самый главный грех?": "Copy Paste"
    "universeQuestion?" : "42"