server:
  port: 8088

spring:
  application:
    name: math-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERV:http://127.0.0.1:8761/eureka/}

management:
 security:
   enabled: false
